name: Scraping X using R

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::RSelenium
    
      - name: docker pull
        run: docker pull selenium/standalone-chrome
      - name: docker and script run
        run: |
          docker run -d -p 4445:4444 selenium/standalone-chrome
          Rscript script.R
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Update data' || echo "Update data"
          git push origin || echo "Update data"
